### ISSUE TITLE
AVX2 build is now broken on GCC 4.9.2

### ISSUE THREAD

**Issue by WojciechMula** [WojciechMula/sse-popcount#14]
GCC 5.3.1 works fine.

**Comment by kimwalisch** [comment]
Hi Wojciech,

I want to test your AVX2 popcount algorithm in my primecount algorithm. For
this purpose I have created a new libpopcnt GitHub repository on which I
will work in the next days. While looking at your
popcnt-avx2-harley-seal.cpp I realise that you are using the 4th iteration
of the Harley Seal algorithm. Looking at your benchmark results I realise
that this algorithm is only fastest past 4096 bytes compared to an unrolled
POPCNT algorithm.

Maybe it would be wise to benchmark the 3rd iteration of the AVX2 Harley
Seal algorithm, with some luck the algorithm would then run faster starting
at 2048 bytes without deteriorating past 4096 bytes (because I think the
algorithm hits the memory/cache botteneck) compared to the 4th iteration of
the AVX2 Harley Seal algorithm. Here is an implementation of the 3rd
iteration of the Harley Seal algorithm:
https://github.com/kimwalisch/primecount/blob/master/include/popcount.hpp#L161

Best regards,
Kim

**Comment by lemire** [comment]
@kimwalisch 

I have added a shorter AVX2 HS...

https://github.com/CountOnes/hamming_weight/commit/2ab07ace5732264120a860f9cd7c643422d1e233

Predictably, the result is slower for long arrays. Of course, if you have short arrays, it might be preferable.

**Comment by kimwalisch** [comment]
Awesome, thanks!

**Comment by WojciechMula** [comment]
@kimwalisch We also tested 5th iteration, but with AVX512F. It's faster for longer inputs.

**Comment by kimwalisch** [comment]
@WojciechMula I cannot find any popcount benchmark results for AVX512. Have you benchmarked it? Is AVX512 popcount faster than AVX2?

**Comment by lemire** [comment]
@kimwalisch 

> Is AVX512 popcount faster than AVX2?

This question is not well posed. Currently, the only available hardware where AVX512 runs is Knights Landing, and it is a system optimized for AVX-512 execution.

**Comment by WojciechMula** [comment]
@kimwalisch We haven't published any benchmark yet, but for sure AVX512 is faster than AVX2. Will post numbers when I'm back home.

And as Daniel said, AVX512 is the main instruction set on KNL. Many AVX2 instructions that are really fast on Skylake and other popular desktop CPUs, on KNL are incredibly slow. Take a look at the latest documents from Agner Fog http://agner.org/optimize/#manuals and compare instructions timing. For example on Skylake PSHUFB both latency and throughput are 1 cycle, on KNL it is 11 cycles (and VPSHUFB is two times slower).

**Comment by WojciechMula** [comment]
@kimwalisch The metric we're using in the project Daniel linked is CPU cycles per 64-bit word. Going to the numbers: popcount of 8192 words, the fastest AVX2 procedure runs at rate 1.12 cycle, while AVX512F runs at 0.33. More than 3 times faster.
